In [2]:
import numpy as np

In [3]:
# create 1's matrix

In [8]:
mx_1s = np.array([[1,1,1], [1,1,1], [1,1,1]])
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [30]:
print(mx_1s.ndim)

2


In [28]:
print(mx_1s.dtype)

int32


In [13]:
# Example 2nd :- create 1's matrix without take elemment

In [14]:
mx_1s = np.ones(5)
print(mx_1s)

[1. 1. 1. 1. 1.]


In [25]:
print(mx_1s.dtype)

int32


In [26]:
print(mx_1s.ndim)

2


In [17]:
# Example 3

In [20]:
mx_1s = np.ones((3, 4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
print(mx_1s.dtype)

int32


In [22]:
# create matrix in integer form

In [23]:
mx_1s = np.ones([3,4], dtype = int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [24]:
mx_1s = np.ones((3,4), dtype = int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [31]:
print(mx_1s.dtype)

int32


In [32]:
# create zeros matrix

In [38]:
mx_os = np.zeros((3,3))
print(mx_os)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [39]:
# Matrix convert into boolean

In [41]:
mx_os = np.zeros((3,3), dtype = bool)
print(mx_os)  # 0 = false

[[False False False]
 [False False False]
 [False False False]]


In [42]:
# Matrix convert into string

In [44]:
mx_os = np.zeros((3,3), dtype = str)
print(mx_os)  # ' ' = false 

[['' '' '']
 ['' '' '']
 ['' '' '']]


In [46]:
em_str = ' '
(em_str)

' '

In [47]:
# create en empty matrix

In [57]:
em_mx = np.empty((3,3))
print((em_mx))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
