In [1]:
import numpy as np

# Concatenate function

In [2]:
arr1 = np.arange(1, 17).reshape(4,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [3]:
arr2 = np.arange(17, 33).reshape(4,4)
print(arr2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [4]:
np.concatenate((arr1, arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

# Column wise concatenate

In [5]:
np.concatenate((arr1, arr2), axis = 0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [6]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

# Row wise concatenate

In [7]:
np.concatenate((arr1, arr2), axis = 1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [8]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

# Add third array

In [9]:
arr3 = np.arange(32, 48).reshape(4,4)
print(arr3)

[[32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]]


In [10]:
np.concatenate((arr1, arr2, arr3))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47]])

In [11]:
np.hstack((arr1, arr2, arr3))

array([[ 1,  2,  3,  4, 17, 18, 19, 20, 32, 33, 34, 35],
       [ 5,  6,  7,  8, 21, 22, 23, 24, 36, 37, 38, 39],
       [ 9, 10, 11, 12, 25, 26, 27, 28, 40, 41, 42, 43],
       [13, 14, 15, 16, 29, 30, 31, 32, 44, 45, 46, 47]])

# SPLIT FUNCTION

In [12]:
np.split(arr1, 2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [13]:
type(np.split(arr1, 2))

list

In [14]:
list1 = np.split(arr1, 2)
list1[0]  # access index 0 element

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Split array row wise

In [15]:
np.split(arr3, 4, axis = 1)

[array([[32],
        [36],
        [40],
        [44]]),
 array([[33],
        [37],
        [41],
        [45]]),
 array([[34],
        [38],
        [42],
        [46]]),
 array([[35],
        [39],
        [43],
        [47]])]

In [16]:
list3= np.split(arr3, 4, axis = 1)
list3[3]

array([[35],
       [39],
       [43],
       [47]])

# Split 1D aray

In [17]:
 d1 = np.array([2, 3, 1, 5, 4])
np.split(d1, [1, 3])

[array([2]), array([3, 1]), array([5, 4])]

In [18]:
d2 = np.array([1,6,3,2,5,9,8])
np.split(d2, [1,4])

[array([1]), array([6, 3, 2]), array([5, 9, 8])]