# Linear algebra :- 1. Invert, 2. Power of matrix, 3. Linear equation, 4. Determinants

# Inverse of matrix using numpy

In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,3], [5,6]])
arr1

array([[1, 3],
       [5, 6]])

In [3]:
np.linalg.inv(arr1)

array([[-0.66666667,  0.33333333],
       [ 0.55555556, -0.11111111]])

In [4]:
arr1.dot(arr1) # another method (matrix product)

array([[16, 21],
       [35, 51]])

In [5]:
np.dot(arr1, arr1)

array([[16, 21],
       [35, 51]])

# Power of matrix

In [6]:
a = np.array([[2,4], [8,9]])
a

array([[2, 4],
       [8, 9]])

In [7]:
np.linalg.matrix_power(a, 2)

array([[ 36,  44],
       [ 88, 113]])

In [8]:
np.linalg.matrix_power(a, -2)

array([[ 0.57653061, -0.2244898 ],
       [-0.44897959,  0.18367347]])

In [9]:
b = np.linalg.inv(a)
b

array([[-0.64285714,  0.28571429],
       [ 0.57142857, -0.14285714]])

In [10]:
np.linalg.matrix_power(b, 2)

array([[ 0.57653061, -0.2244898 ],
       [-0.44897959,  0.18367347]])

# Solve Linear equation using numpy

In [11]:
a = np.array([[3,1], [1,2]])
a

array([[3, 1],
       [1, 2]])

In [12]:
b = np.array([9,8])
b

array([9, 8])

In [13]:
np.linalg.solve(a,b)

array([2., 3.])

In [14]:
x = np.array([[6, 2, -5], [3, 3, -2], [7, 5, -32]])
x

array([[  6,   2,  -5],
       [  3,   3,  -2],
       [  7,   5, -32]])

In [15]:
y = np.array([13, 13, 26])
y

array([13, 13, 26])

In [16]:
np.linalg.solve(x,y)

array([ 1.00931677,  3.27018634, -0.08074534])

# Determinant()

In [17]:
m = np.array([[1,2], [3,4]])
m

array([[1, 2],
       [3, 4]])

In [18]:
np.linalg.det(m)

-2.0000000000000004

In [19]:
round(np.linalg.det(m))

-2

In [20]:
m = np.array([[1,2,3], [4, 5, 6], [7, 8 ,9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np.linalg.det

<function numpy.linalg.det(a)>

In [24]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
np.linalg.inv(a)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [ ]:
np.linalg.matrix_power