In [1]:
# create 1D array

In [2]:
import numpy as np

In [3]:
arr_1d = np.array([1, 2, 3, 4])
print(arr_1d)

[1 2 3 4]


In [4]:
print(type(arr_1d))

<class 'numpy.ndarray'>


In [5]:
type(arr_1d)

numpy.ndarray

In [6]:
arr_1d.ndim

1

In [7]:
# 1 = 1 dimensional array

In [8]:
# Create 2D array (list of list)

In [9]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
type(arr_2d)

numpy.ndarray

In [11]:
arr_2d.ndim

2

In [12]:
arr_2d.size

8

In [13]:
arr_1d.size

4

In [14]:
arr_1d.shape

(4,)

In [15]:
arr_2d.shape

(2, 4)

In [16]:
arr_1d.dtype

dtype('int32')

In [17]:
arr_2d.dtype

dtype('int32')

In [18]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
import calendar as cl
year = 2022
print(cl.year(year))

AttributeError: module 'calendar' has no attribute 'year'