In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Add matrix

In [3]:
np.add(arr1, arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [4]:
arr1 + arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

# Sutract matrix

In [5]:
np.subtract(arr1, arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [6]:
arr1 - arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Division matrix

In [7]:
np.divide(arr1, arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
arr1 / arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Multiplication matrix

In [9]:
arr1 * arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [10]:
np.multiply(arr1, arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

# Matrix product

In [11]:
arr1 @ arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [12]:
np.dot(arr1, arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

# Maximum value in matrix

In [13]:
arr1.max()

9

In [14]:
arr2.max()

9

# Maximum index

In [15]:
 arr1.argmax()

8

In [16]:
arr2.argmax()

8

# Maximum value in column

In [46]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
arr1.max(axis = 0)

array([7, 8, 9])

In [18]:
arr2.max(axis = 0)

array([7, 8, 9])

# Maximum value in row

In [19]:
arr1.max(axis = 1)

array([3, 6, 9])

In [20]:
arr2.max(axis = 1)

array([3, 6, 9])

# Minimum value in matrix

In [21]:
arr1.min()

1

In [22]:
arr2.min()

1

# Minimum index

In [23]:
arr1.argmin()

0

In [24]:
arr2.argmin()

0

# Minimum value in column and row

In [25]:
arr1.min(axis = 0)

array([1, 2, 3])

In [26]:
arr2.min(axis = 0)

array([1, 2, 3])

In [27]:
arr1.min(axis = 1)

array([1, 4, 7])

In [28]:
arr2.min(axis = 1)

array([1, 4, 7])

# Sum of Every element in matrix

In [29]:
np.sum(arr1)

45

In [30]:
np.sum(arr2)

45

# Sum of every column in matrix

In [31]:
np.sum(arr1, axis = 0)

array([12, 15, 18])

In [32]:
np.sum(arr2, axis = 1)

array([ 6, 15, 24])

# Sum of every row in matrix

In [33]:
np.sum(arr1, axis = 1)

array([ 6, 15, 24])

In [34]:
np.sum(arr2, axis = 1)

array([ 6, 15, 24])

# Average 

In [35]:
np.mean(arr1)

5.0

In [36]:
np.mean(arr2)

5.0

# Square root

In [37]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [38]:
np.sqrt(arr2)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

# Standard deviation

In [39]:
np.std(arr1)

2.581988897471611

In [40]:
np.std(arr2)

2.581988897471611

# Exponential

In [41]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

# Logarithm

In [42]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [43]:
np.log(arr2)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

# Log base 10 (log10)

In [44]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [45]:
np.log10(arr2)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])