# Random sampling with numpy

In [1]:
import numpy as np
import random

In [2]:
np.random.random(1)

array([0.27146833])

In [3]:
np.random.random(3)

array([0.18319825, 0.33006611, 0.99307036])

In [4]:
np.random.random(3).ndim

1

In [5]:
np.random.random(1).ndim


1

In [6]:
np.random.random((3,3))

array([[0.77947069, 0.5256839 , 0.00569283],
       [0.74157898, 0.66077737, 0.46087418],
       [0.25275046, 0.69954301, 0.40293271]])

In [7]:
np.random.random((3,3)).ndim

2

In [8]:
np.random.randint(1)

0

In [28]:
np.random.randint(1, 4, (10, 10)) # 1,4 is range and (10,10) is shape

array([[3, 3, 2, 2, 3, 3, 1, 3, 1, 3],
       [1, 2, 1, 3, 3, 2, 3, 1, 3, 2],
       [3, 1, 1, 3, 2, 1, 2, 3, 1, 1],
       [1, 2, 3, 1, 2, 3, 3, 2, 2, 1],
       [2, 1, 3, 2, 1, 3, 1, 3, 3, 2],
       [1, 2, 1, 1, 1, 1, 1, 2, 1, 2],
       [2, 2, 1, 3, 3, 1, 3, 3, 1, 1],
       [3, 3, 3, 3, 2, 3, 3, 2, 3, 3],
       [3, 2, 1, 1, 3, 1, 3, 3, 1, 2],
       [2, 3, 1, 2, 1, 2, 2, 1, 1, 3]])

In [10]:
np.random.randint(1,4,(2,4,4))  # Create 3D array

array([[[2, 1, 1, 2],
        [3, 1, 1, 1],
        [3, 3, 3, 1],
        [1, 3, 2, 1]],

       [[1, 1, 3, 3],
        [2, 1, 2, 1],
        [2, 3, 1, 1],
        [2, 2, 1, 1]]])

In [11]:
np.random.seed()   # seed function access always same value as above if we use same range and shape
np.random.randint(1,4,(2,4,4))

array([[[1, 2, 3, 3],
        [1, 3, 3, 1],
        [2, 1, 3, 1],
        [1, 1, 2, 3]],

       [[1, 1, 1, 1],
        [3, 2, 2, 3],
        [3, 3, 3, 3],
        [2, 3, 2, 1]]])

In [12]:
np.random.seed()  
np.random.randint(1,4,(2,4,4))

array([[[3, 1, 2, 1],
        [1, 2, 3, 2],
        [3, 2, 3, 1],
        [1, 1, 3, 3]],

       [[2, 1, 3, 1],
        [3, 3, 1, 1],
        [3, 3, 1, 2],
        [3, 2, 2, 1]]])

In [13]:
np.random.rand(5) # rand() function gives 0 to 1 value

array([0.65185874, 0.87397087, 0.0904079 , 0.98343284, 0.10738269])

In [14]:
np.random.rand(4,4) 

array([[0.69376558, 0.38945633, 0.96628493, 0.74511116],
       [0.79396266, 0.60351868, 0.03192704, 0.07609346],
       [0.20652045, 0.06103964, 0.12390807, 0.53461934],
       [0.16418404, 0.99079066, 0.99973776, 0.60654291]])

In [15]:
x = [1, 2, 3, 4, 5]
np.random.choice(x)

4

In [16]:
x = [1, 2, 4, 6, 5, 7, 10, 9, 13]
np.random.choice(x)

2

In [17]:
np.random.seed(60)
for i in range(20):
    print(np.random.choice(x))

2
10
6
13
2
4
2
9
13
7
4
13
10
6
4
7
1
6
5
1


In [18]:
np.random.randn(4, 4)  # randn() function gives both the positive and negative value

array([[-0.94330718, -0.72037043,  2.2812894 ,  0.03496727],
       [-0.67456867,  0.21813782,  1.16688402,  0.2801483 ],
       [ 0.56085277,  0.05761436,  0.2650429 , -2.21096759],
       [-0.02866144, -0.26349276,  1.31209035,  0.94339814]])

In [19]:
x = [ 7, 10, 13,  1,  5,  2,  4,  9,  6]
np.random.permutation(x)


array([ 6,  7,  5, 13,  4, 10,  1,  2,  9])

In [23]:
np.random.seed(60)
for i in range(20):
    print(np.random.choice(x))

10
4
1
6
10
13
10
9
6
2
13
6
4
1
13
2
7
1
5
7


In [27]:
np.random.seed(60)
for i in range(44):
    print(np.random.choice(x))

10
4
1
6
10
13
10
9
6
2
13
6
4
1
13
2
7
1
5
7
4
4
2
9
7
13
2
6
9
5
7
9
7
4
13
13
7
6
10
4
6
13
13
9


In [39]:
np.random.seed(10)
np.random.randn(3,4)

array([[ 1.3315865 ,  0.71527897, -1.54540029, -0.00838385],
       [ 0.62133597, -0.72008556,  0.26551159,  0.10854853],
       [ 0.00429143, -0.17460021,  0.43302619,  1.20303737]])

In [40]:
np.random.seed(10)
np.random.randn(3,4)

array([[ 1.3315865 ,  0.71527897, -1.54540029, -0.00838385],
       [ 0.62133597, -0.72008556,  0.26551159,  0.10854853],
       [ 0.00429143, -0.17460021,  0.43302619,  1.20303737]])

In [46]:
np.random.seed(10)
np.random.permutation([1,23,4,5,6,7,8,9,0])

array([ 0,  4,  7,  8,  5, 23,  1,  9,  6])

In [45]:
np.random.seed(10)
np.random.permutation([1,23,4,5,6,7,8,9,0])

array([ 0,  4,  7,  8,  5, 23,  1,  9,  6])

In [44]:
np.random.permutation([1,23,4,5,6,7,8,9,0])

array([ 5,  9,  6,  8,  0,  4, 23,  7,  1])

In [55]:
np.random.rand(3,34,5)

array([[[0.82868133, 0.04689632, 0.62628715, 0.54758616, 0.819287  ],
        [0.19894754, 0.8568503 , 0.35165264, 0.75464769, 0.29596171],
        [0.88393648, 0.32551164, 0.1650159 , 0.39252924, 0.09346037],
        [0.82110566, 0.15115202, 0.38411445, 0.94426071, 0.98762547],
        [0.45630455, 0.82612284, 0.25137413, 0.59737165, 0.90283176],
        [0.53455795, 0.59020136, 0.03928177, 0.35718176, 0.07961309],
        [0.30545992, 0.33071931, 0.7738303 , 0.03995921, 0.42949218],
        [0.31492687, 0.63649114, 0.34634715, 0.04309736, 0.87991517],
        [0.76324059, 0.87809664, 0.41750914, 0.60557756, 0.51346663],
        [0.59783665, 0.26221566, 0.30087131, 0.02539978, 0.30306256],
        [0.24207588, 0.55757819, 0.56550702, 0.47513225, 0.29279798],
        [0.06425106, 0.97881915, 0.33970784, 0.49504863, 0.97708073],
        [0.44077382, 0.31827281, 0.51979699, 0.57813643, 0.85393375],
        [0.06809727, 0.46453081, 0.78194912, 0.71860281, 0.58602198],
        [0.03709441,